version: '3'
services:
  web:
    container_name: dotenetCore
    build: .
    ports:
        - "80:5000"
        - "5000:5000"
        - "443:5001"
    depends_on:
        - postgres
    environment:
      - ASPNETCORE_URLS=https://+;http://+;
      - ConnectionStrings__default="Server=the-production-database-server; Database=DbContextFactorySample2; Trusted_Connection=True;"
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql